title: Markdown in Just the Docs
description: Exsercises in Just the Docs
theme: just-the-docs

url: https://jandag.github.io/JustTheDocs

aux_links:
  Template Repository: https://github.com/jandag/JustTheDocs
